services:
  postgres:
   image: postgres:16
   container_name: dev-postgres
   environment:
    POSTGRES_DB: express_blog
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    TZ: Asian/Ho_Chi_Minh
   ports:
    - "5435:5432"
   volumes:
    - pgdata:/var/lib/postgresql/data
   healthcheck:
    test: ["CMD-SHELL", "pg_isready -U postgres"]
    interval: 10s
    timeout: 5s
    retries: 5

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  pgdata: